"""create initial route tables

Revision ID: 2926aa703228
Revises: 88bec29e453f
Create Date: 2026-06-02 18:46:02.901246

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2926aa703228"
down_revision: str | Sequence[str] | None = "88bec29e453f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("driver_id", sa.String(length=128), nullable=True),
        sa.Column("original_stop_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'ready', 'optimizing', 'optimized', 'failed', 'archived')",
            name="route_status_valid",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "optimization_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("algorithm", sa.String(length=64), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'canceled')",
            name="optimization_job_status_valid",
        ),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_optimization_jobs_route_id"), "optimization_jobs", ["route_id"], unique=False
    )
    op.create_table(
        "stops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("external_order_id", sa.String(length=128), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("service_time_seconds", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("time_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_stops_location_gist", "stops", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_stops_route_id"), "stops", ["route_id"], unique=False)
    op.create_index(
        "ix_stops_route_id_sequence_number", "stops", ["route_id", "sequence_number"], unique=True
    )
    op.create_table(
        "route_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("optimization_job_id", sa.UUID(), nullable=True),
        sa.Column("metric_type", sa.String(length=32), nullable=False),
        sa.Column("total_distance_meters", sa.Integer(), nullable=False),
        sa.Column("total_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("drive_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("service_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("backtrack_count", sa.Integer(), nullable=False),
        sa.Column("estimated_savings_distance_meters", sa.Integer(), nullable=False),
        sa.Column("estimated_savings_duration_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "metric_type IN ('original', 'optimized', 'comparison')", name="route_metric_type_valid"
        ),
        sa.ForeignKeyConstraint(
            ["optimization_job_id"], ["optimization_jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_route_metrics_optimization_job_id"),
        "route_metrics",
        ["optimization_job_id"],
        unique=False,
    )
    op.create_index(op.f("ix_route_metrics_route_id"), "route_metrics", ["route_id"], unique=False)
    op.create_table(
        "route_sequences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("stop_id", sa.UUID(), nullable=False),
        sa.Column("optimization_job_id", sa.UUID(), nullable=True),
        sa.Column("sequence_type", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sequence_type IN ('original', 'optimized', 'driver_adjusted')",
            name="route_sequence_type_valid",
        ),
        sa.ForeignKeyConstraint(
            ["optimization_job_id"], ["optimization_jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stop_id"], ["stops.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_route_sequences_optimization_job_id"),
        "route_sequences",
        ["optimization_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_sequences_route_id"), "route_sequences", ["route_id"], unique=False
    )
    op.create_index(
        "ix_route_sequences_route_type_position",
        "route_sequences",
        ["route_id", "sequence_type", "position"],
        unique=True,
    )
    op.create_index(
        "ix_route_sequences_route_type_stop",
        "route_sequences",
        ["route_id", "sequence_type", "stop_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_route_sequences_stop_id"), "route_sequences", ["stop_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_route_sequences_stop_id"), table_name="route_sequences")
    op.drop_index("ix_route_sequences_route_type_stop", table_name="route_sequences")
    op.drop_index("ix_route_sequences_route_type_position", table_name="route_sequences")
    op.drop_index(op.f("ix_route_sequences_route_id"), table_name="route_sequences")
    op.drop_index(op.f("ix_route_sequences_optimization_job_id"), table_name="route_sequences")
    op.drop_table("route_sequences")
    op.drop_index(op.f("ix_route_metrics_route_id"), table_name="route_metrics")
    op.drop_index(op.f("ix_route_metrics_optimization_job_id"), table_name="route_metrics")
    op.drop_table("route_metrics")
    op.drop_index("ix_stops_route_id_sequence_number", table_name="stops")
    op.drop_index(op.f("ix_stops_route_id"), table_name="stops")
    op.drop_index("ix_stops_location_gist", table_name="stops", postgresql_using="gist")
    op.drop_table("stops")
    op.drop_index(op.f("ix_optimization_jobs_route_id"), table_name="optimization_jobs")
    op.drop_table("optimization_jobs")
    op.drop_table("routes")
    # ### end Alembic commands ###
